/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
Author: Pitstop3D - Trucks (https://sketchfab.com/pitstop3d-trucks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/volkswagen-constellation-light-cab-chassis-0ab4bb61c34e43c9813571c7f5e823de
Title: Volkswagen Constellation Light Cab-Chassis
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.24]} scale={[1, 1, 0.77]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Black} />
      </group>
      <group position={[0, 0, 0.32]} scale={[1, 1, 0.72]}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Mirrors} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Tail_Lights} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Main_Paint} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Indicators} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Mirrors} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Black} position={[0, 0, 0.32]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Rims} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Rims} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Rims} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Rims} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Chrome} position={[-0.02, -1.46, -0.23]} scale={[1.53, 1.79, 1.79]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Black} scale={[5.53, 1, 1]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
