/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 notepad.gltf
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/single-spiral-notepad-80299283fefc44649ae00bf4992b7ba2
Title: Single spiral notepad
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Notepad(props) {
  const { nodes, materials } = useGLTF('/notepad.gltf')
  return (
    <group {...props} dispose={null} scale={12} rotation={[0, 0, Math.PI / 2]}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['M_notebook_closed_clean.001']} position={[-0.14, 0, 0]} rotation={[Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_58.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_72.geometry} material={materials['M_notebook_closed_clean.001']} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['M_notebook_closed_clean.001']} />
    </group>
  )
}

useGLTF.preload('/notepad.gltf')
