/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 oil_bottle.gltf
Author: RaynaudL (https://sketchfab.com/fts_ltx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/motor-oil-bottle-gallon-lowpoly-remake-291a9aa19af44c3296375eb3a30e99ae
Title: Motor Oil bottle gallon - lowpoly remake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function OilBottle(props) {
  const { nodes, materials } = useGLTF('/oil_bottle.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['model_diffuse-material'].geometry} material={materials.model_diffuse} position={[0, 0, -1.5]} scale={12} />
      </group>
    </group>
  )
}

useGLTF.preload('/oil_bottle.gltf')
