/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 printer.gltf
Author: CG Buzz (https://sketchfab.com/Tapan_S)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/printer-low-poly-8a3a68f84f4d4a34973b527875a7314b
Title: Printer- Low Poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Printer(props) {
  const { nodes, materials } = useGLTF('/printer.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Printer_Printer_0.geometry} material={materials.Printer} rotation={[-Math.PI / 2, 0, 0]} scale={1200} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/printer.gltf')
